// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwnP0fHETOhfMyLO8vu5CBt9_z6RVZ4Ok',
    appId: '1:889164346366:web:190f2ad5f7ca2c079c86af',
    messagingSenderId: '889164346366',
    projectId: 'flash-chat-b188c',
    authDomain: 'flash-chat-b188c.firebaseapp.com',
    storageBucket: 'flash-chat-b188c.appspot.com',
    measurementId: 'G-MNP0EZVEN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkZ_imefbgWZ5z-pk5DnQ_SOGoHyJCdsk',
    appId: '1:889164346366:android:8dae81d9fe0e38dd9c86af',
    messagingSenderId: '889164346366',
    projectId: 'flash-chat-b188c',
    storageBucket: 'flash-chat-b188c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2iFI3rTciLwej4MPyPq6xfsNzX_qov9E',
    appId: '1:889164346366:ios:e179f96936033b959c86af',
    messagingSenderId: '889164346366',
    projectId: 'flash-chat-b188c',
    storageBucket: 'flash-chat-b188c.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2iFI3rTciLwej4MPyPq6xfsNzX_qov9E',
    appId: '1:889164346366:ios:e179f96936033b959c86af',
    messagingSenderId: '889164346366',
    projectId: 'flash-chat-b188c',
    storageBucket: 'flash-chat-b188c.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwnP0fHETOhfMyLO8vu5CBt9_z6RVZ4Ok',
    appId: '1:889164346366:web:db521b9f65c1087d9c86af',
    messagingSenderId: '889164346366',
    projectId: 'flash-chat-b188c',
    authDomain: 'flash-chat-b188c.firebaseapp.com',
    storageBucket: 'flash-chat-b188c.appspot.com',
    measurementId: 'G-V2210R935F',
  );

}